services:
  - type: web
    name: stock-bot
    env: python
    pythonVersion: 3.13
    buildCommand: pip install --upgrade --force-reinstall -r requirements.txt
    startCommand: python stock_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false